### ISSUE TITLE
I don't know what happened

### ISSUE THREAD

**Issue by ecnivo** [Bimde/Blackjack-Server#35] opened 2015-12-08 17:46 UTC
![image](https://cloud.githubusercontent.com/assets/10538710/11663324/93e84092-9da9-11e5-90ff-56ccb5c90376.png)
I don't know what happened, but you should probably know about this in some way, shape, or  form.

**Comment by pcjl** [comment] 2015-12-08 17:57
Pretty sure this is a problem with your client, we're sending the correct message ($ 1 bets 10).

**Comment by Bimde** [comment] 2015-12-08 18:48
If the server is crashing / throwing exceptions, regardless of what the clients are doing, this might be an actual bug. This will be investigated + fixed  tonight.

**Comment by Bimde** [comment] 2015-12-08 18:50
This looks like the message queue is trying to remove a message when there are no messages left. This is potentially due to synchronization issues (with messages being added + removed at the same time from different threads)

**Comment by xuwilliam01** [comment] 2015-12-08 18:55
Just add an if statement with queue.size. it should fix it. This wont fix
the problem if some messages arent being queued at all.

**Comment by pcjl** [comment] 2015-12-08 18:59
Whoops, I misread this. Thought this was the console output of a client rather than a server.

**Comment by Bimde** [comment] 2015-12-08 19:03
@Williamxu98 This is already being done (look at the Server#actionPerformed method). The problem is probably related to the message queue being changed in between the check and removing the message from the queue. A potential solution is to use a different data structure that is thread safe. I.e. a [LinkedBlockingDeque](http://docs.oracle.com/javase/8/docs/api/java/util/concurrent/LinkedBlockingDeque.html)

**Comment by Bimde** [comment] 2015-12-08 19:10
@ecnivo Was this using the latest version (after our discussion about using master)? And is it possible to reproduce this error?

**Comment by xuwilliam01** [comment] 2015-12-08 19:13
He was using an outdated version when he showed me the error. Try
reproducing it in the new version

**Comment by ecnivo** [comment] 2015-12-08 22:06
I pulled master during fifth and it was broken af, but I'm on stable at home (latest), and I haven't seen anything weird.

**Comment by pcjl** [comment] 2015-12-08 23:45
Could you send logs of what is broken with master?

**Comment by ecnivo** [comment] 2015-12-09 03:57
Nothing. I pressed "run" and nothing was printed, and it just stopped running. Now it's fine.

**Closed as completed** 2015-12-09 04:28 UTC
Labels: bug

**Comment by ecnivo** [comment] 2015-12-09 12:52
Silly me, I didn't realize that you guys had more game rooms and ran Server instead of CentralServer.
